spring:
  cloud:
    services:
      registrationMethod: route

security:
  basic:
    enabled: false


#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    preferIpAddress: true
#    appname: shopizer-sm-shop
